### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by evenfrost** [SamVerschueren/listr-input#4]
On Ubuntu 16.10, using Terminal. Installed `listr`, `listr-input` and `got` on a newly created project and ran example from readme. `Retrieving data step` shows loading animation, but there is no prompt for user:
![screenshot from 2017-11-15 15-05-45](https://user-images.githubusercontent.com/3055750/32835289-9e383e44-ca16-11e7-9cb0-c4718a6e50f6.png)

**Comment by SamVerschueren** [comment]
Sorry for the late reply! I tracked down the issue and the reason is that the example uses a `C` (`Credentials`) in the message. If you use something else like `Foo` for instance, it works. I'm looking into fixing this.

**Comment by SamVerschueren** [comment]
Should be fixed in `0.1.3`.
